#cloud-config
autoinstall:
 version: 1
 storage:
  layout:
   name: lvm
   policy: all
 user-data:
  users: ['']
 locale: "de_CH.UTF-8"
 keyboard:
  layout: "ch"
 source:
  search_drivers: true
  id: ubuntu-desktop-minimal
 ssh:
  install-server: true
  allow-pw: true
 drivers:
  install: true
 packages:
  - openssh-server
 timezone: Europe/Zurich
 updates: all
 shutdown: reboot
 late-commands:
  - curtin in-target -- apt update
  - curtin in-target -- apt -y upgrade
  - curtin in-target -- wget get -p https://github.com/danielzoller20/BstellOnlineMonitor/archive/refs/heads/master.zip -O /tmp/BstellOnlineMonitor.zip
  - curtin in-target -- unzip /tmp/BstellOnlineMonitor.zip -d /tmp
  - curtin in-target -- mkdir /monitoring
  - curtin in-target -- mv /tmp/BstellOnlineMonitor-master/* /monitoring
  - curtin in-target -- wget https://raw.githubusercontent.com/danielzoller20/KassaBuntu/refs/heads/main/applyEnergySettings.sh -O /monitoring/applyEnergySettings.sh
  - curtin in-target -- chmod +x /tmp/applyEnergySettings.sh 